### ISSUE TITLE
Add support to gClef8va and bridgeClef 

### ISSUE THREAD

**Issue by charlesneimog** [DigiScore/neoscore#96]
Hi, 

I believe I can do it myself and make a PR. But maybe this is already implemented, and I could not find it!

Thanks

- [ ] add clefs `bridgeClef` for draws
- [ ] and `gClef8va` to instruments like piccollo.

**Comment by Xavman42** [comment]
Here's one possible way to implement custom SMuFL clefs

```
from neoscore.core import neoscore
from neoscore.core.units import Mm, ZERO
from neoscore.western.clef import Clef
from neoscore.western.clef_type import ClefType, KeySignatureLayout
from neoscore.western.staff import Staff

neoscore.setup()
POSITION = (Mm(0), Mm(0))
staff = Staff(POSITION, None, Mm(80))
_sharp_positions: KeySignatureLayout = {
    "f": (0, 0),
    "c": (1, 1.5),
    "g": (2, -0.5),
    "d": (3, 1),
    "a": (4, 2.5),
    "e": (5, 0.5),
    "b": (6, 2),
}
_flat_positions: KeySignatureLayout = {
    "b": (0, 2),
    "e": (1, 0.5),
    "a": (2, 2.5),
    "d": (3, 1),
    "g": (4, 3),
    "c": (5, 1.5),
    "f": (6, 3.5),
}
my_clef = ClefType('gClef8va', 3, 5, _sharp_positions, _flat_positions)
clef = Clef(ZERO, staff, my_clef)
neoscore.show(display_page_geometry=False)
```
And here's the result
![image](https://user-images.githubusercontent.com/79334532/214080438-a63a9f09-789c-407c-b226-5933679fc338.png)

**Comment by ajyoon** [comment]
@Xavman42 your solution is correct, though instead of `5` it should used `8.5` as its middle-C position. This is a very easy add so I just pushed an implementation for this, along with bridge clef, in [18c5b3d](https://github.com/DigiScore/neoscore/commit/18c5b3daf2da76d68afba135e1b084e75a0cdf26). @charlesneimog we probably won't release this for a couple weeks, so if you need the functionality now you can pretty easily copy/paste from that commit.

**Comment by charlesneimog** [comment]
Great, thanks!!!
